### ISSUE TITLE
"Error" occurs when typing "fun" string.

### ISSUE THREAD

**Issue by Ionizing** [wsdjeg/SpaceVim#121]
### Expected behavior, english is recommend
When editting .m file (MATLAB script) and type "fun", it should show the completion like "function" while it shows the error described in the following.

### Environment Information
- OS: Ubuntu 16.10
- vim version: 8.0 (Compiled Jan 16 2017)
- neovim version: None

### The reproduce ways from Vim starting (Required!)
I use spacevim to write matlab scrpits. When I am typing "fun" or "funct", space vim gives errors as follow:
`Error detected while processing function <SNR>168_my_complete_done
line xx:
E735: Can only compare Dictionary with Dictionary
Press ENTER or type command to continue`

and when I press ENTER, it gives:

`E15: Invalid expression: get(v:,'completed_item','') ==# ''
Press ENTER or type command to continue`

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()
`"a.m" [New] 0L, 0C written
Already at oldest change
E486: Pattern not found: \<RequirePackage\>\C
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E735: Can only compare Dictionary with Dictionary
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E15: Invalid expression: get(v:,'completed_item','') ==# ''
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E735: Can only compare Dictionary with Dictionary
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E15: Invalid expression: get(v:,'completed_item','') ==# ''
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E735: Can only compare Dictionary with Dictionary
Error detected while processing function <SNR>210_my_complete_done:
line    1:
E15: Invalid expression: get(v:,'completed_item','') ==# ''
`

**Comment by wsdjeg** [comment]
it has been fixed, see https://github.com/SpaceVim/SpaceVim/blob/lang/php/config/plugins/neosnippet.vim
I have change `get(v:,'completed_item','') ==# ''` to `!empty(get(v:,'completed_item',''))`. you should update SpaceVim.

**Comment by Ionizing** [comment]
But I just updated spacevim about a hr ago.    And the problem still occurs.

Ionizing Radiation

On Jan 17, 2017, at 23:12, Wang Shidong <notifications@github.com<mailto:notifications@github.com>> wrote:


it has been fixed, see https://github.com/SpaceVim/SpaceVim/blob/lang/php/config/plugins/neosnippet.vim
I have change get(v:,'completed_item','') ==# '' to !empty(get(v:,'completed_item','')). you should update SpaceVim.

-

**Comment by wsdjeg** [comment]
@IonizingRadiation you can check the context in `~/.vim/config/plugins/neosnippet.vim`.

**Comment by Ionizing** [comment]
@wsdjeg I checked `~/.vim/config/plugins/neosnippet.vim` just now and you were right--it was not up-to-date. When I replaced `if get(v:,'completed_item','') ==# ''` (Line 16) by `if !empty(get(v:,'completed_item',''))`, the bug was solved. Thank you very much.

But one more question, why didn't `git` update it when running `.vim/install.sh` while console still gives:

> $ cd .vim
> $ ./install.sh
> Already up-to-date.
> Successfully update SpaceVim
> Installed SpaceVim for vim
> Installed SpaceVim for neovim

I am confused and maybe I should study further on `git`.
Look forward to your reply, thank you.

**Comment by wsdjeg** [comment]
you should check your branch, if it is dev, every thing is ok. or  you can just run git pull.

and make sure your `~/.vim` is a link to `~/.SpaceVim`

**Comment by Ionizing** [comment]
@wsdjeg Yes, the local branch is `* dev`

**Comment by wsdjeg** [comment]
It should be the usage of git. I cannot reproduce this issue.
