### ISSUE TITLE
init.toml background  fail to change  background color

### ISSUE THREAD

**Issue by phiysng** [wsdjeg/SpaceVim#1737]
In the initial init.toml configuration
```
# set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
```
if I set     background = "light"  ,it doesn't works;
Instead , if i change     **background**  to **colorscheme_bg** , It works.
 
![default](https://user-images.githubusercontent.com/17352051/40350840-86478d34-5ddd-11e8-94a3-f8c3b609d134.png)

**Comment by wsdjeg** [comment]
This is a bug of SpaceVim, and in old version, we can use `g:spacevim_colorscheme_bg` to change the background, and in the latest version, we should use `colorscheme_bg` instead of `background`, This should be fixed in quick start guide.

**Comment by xiuliren** [comment]
`background="light"` still do not work for me, I have to use `colorscheme_bg="light"`.

**Comment by wsdjeg** [comment]
yes, we need to use colorscheme _bg

**Comment by xiuliren** [comment]
even `colorscheme_bg` is not working for latest version

**Comment by wsdjeg** [comment]
As github do not support reopen issue from email, please use new issue for bug report.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] init.toml background fail to change background color (#1737)
发件人：Jingpeng Wu
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,State change


even colorscheme_bg is not working for latest version

―

**Comment by xiuliren** [comment]
now, `colorscheme_bg` works for the latest version.

**Comment by 108806** [comment]
How can I change background color to custom one? ie colorsheme_bg = "#000000" is not working at all.

**Comment by wsdjeg** [comment]
@108806 a feature request?

**Comment by 108806** [comment]
Yes, please, I want it black. The darkest working bg I could get by hacking themes was 101010.

**Comment by wsdjeg** [comment]
please use new issue for feature request.
