### ISSUE TITLE
Code runner in java

### ISSUE THREAD

**Issue by matthewcm** [wsdjeg/SpaceVim#2497]
## Expected behavior, english is required
Expecting main function of current java program in the buffer to be run
## The reproduce ways from Vim starting (Required!)
open vim in Directory with java file.
SPC l r m - to run main code runner

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.1.751
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vimrc

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['drewtempelmeyer/palenight.vim', {'name': 'drewtempelmeyer/palenight.vim', 'merged': 0}], ['vimwiki/vimwiki', {'name': 'vimwiki/vimwiki', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tech/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-javacomplete2'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  window_leader = ''
  window_smartclose = ''
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:29:54] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [15:29:54] [ Info ] Startup with argv: ['Hello.java']
[ SpaceVim ] [15:29:54] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [15:29:54] [ Info ] start to apply config [glob]
[ SpaceVim ] [15:29:55] [ Info ] Start to find root for: /home/tech/dev/Java/Hello.java
[ SpaceVim ] [15:29:55] [ Info ]         (.git/):/home/tech/dev/Java/.git/
[ SpaceVim ] [15:29:55] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:29:55] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:29:59] [ Info ] Start to find root for: /home/tech/dev/Java/__runner__
[ SpaceVim ] [15:29:59] [ Info ]         (.git/):/home/tech/dev/Java/.git/
[ SpaceVim ] [15:29:59] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:29:59] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:29:59] [ Info ]    cmd:'java -cp ''/home/tech/.cache/vimfiles/repos/github.com/wsdjeg/JavaUnit.vim/bin:.'' Hello '
[ SpaceVim ] [15:30:13] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:30:43] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:34:11] [ Info ] Start to find root for: /home/tech/dev/Java/SpaceVimLayers
[ SpaceVim ] [15:34:11] [ Info ]         (.git/):/home/tech/dev/Java/.git/
[ SpaceVim ] [15:34:11] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:35:39] [ Info ] change to root:/home/tech/dev/Java
[ SpaceVim ] [15:35:45] [ Info ] Start to find root for: /tmp/vg43pDQ/3/issue_report.md
[ SpaceVim ] [15:35:45] [ Info ] change to root:/home/tech/dev/Java
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![cr_issue2](https://user-images.githubusercontent.com/13544609/51689546-ce941700-1fee-11e9-9987-60d213bebca9.png)

**Comment by matthewcm** [comment]
I thought the issue could be because it was not in the correct directory.
So I made an empty git repository, as I saw that the project root directory is chosen by looking for .git files.

However, it does appear that it is running java -cp '/home/tech/.cache/vimfiles/repos/github.com/wsdjeg/JavaUnit.vim/bin:.' " Hello "
with spaces in the file name.
Running this command without those spaces in the command line fixes this problem.

**Comment by matthewcm** [comment]
So has this been solved? I'm currently trying to solve this issue myself, by fixing the whitespace around the filename string, I have little experience with vimscript, but if I solve it I can send a full request

**Comment by wsdjeg** [comment]
This issue has been fixed.

________________________________
wsdjeg@outlook.com

**Comment by qwetboy10** [comment]
I'm still having this issue

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Enter a java file. Press SPC l r m
It prints this

```
[Running] java -cp ".:/home/tristan/.cache/vimfiles/repos/github.com/wsdjeg/JavaUnit.vim/bin:" prob03 

--------------------
Error: Could not find or load main class prob03
Caused by: java.lang.ClassNotFoundException: prob03

[Done] exited with code=1 in 0.099576 seconds
```
## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 8
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 0
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Fira Code:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tristan/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-java'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:04:28] [ Info ] Startup with no argv, current dir is used: ~/RandomCode
[ SpaceVim ] [17:04:28] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [17:04:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:04:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [17:04:29] [ Info ] Start to find root for: 
[ SpaceVim ] [17:04:29] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:04:29] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:29] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:04:29] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:29] [ Info ] Start to find root for: /home/tristan/RandomCode/vimfiler:default
[ SpaceVim ] [17:04:29] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:04:29] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:36] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:36] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:36] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:36] [ Info ] Start to find root for: /home/tristan/RandomCode/CodeWars16/prob03.java
[ SpaceVim ] [17:04:36] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:04:36] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:42] [ Info ] Start to find root for: /home/tristan/RandomCode/__runner__
[ SpaceVim ] [17:04:42] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:04:42] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:42] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:42] [ Info ]    cmd:'java -cp ".:/home/tristan/.cache/vimfiles/repos/github.com/wsdjeg/JavaUnit.vim/bin:" prob03 '
[ SpaceVim ] [17:04:54] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:54] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:56] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:04:56] [ Info ] Start to find root for: 
[ SpaceVim ] [17:04:56] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:04:56] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:05:06] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:08:11] [ Info ] Start to find root for: /home/tristan/RandomCode/__runner__
[ SpaceVim ] [17:08:11] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:08:11] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:08:11] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:08:11] [ Info ]    cmd:'java -cp ".:/home/tristan/.cache/vimfiles/repos/github.com/wsdjeg/JavaUnit.vim/bin:" prob03 '
[ SpaceVim ] [17:09:29] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:10:15] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:10:17] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:10:17] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:10:17] [ Info ] Start to find root for: 
[ SpaceVim ] [17:10:17] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:10:17] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:11:17] [ Info ] Start to find root for: 
[ SpaceVim ] [17:11:17] [ Info ]         (.git/):/home/tristan/RandomCode/.git/
[ SpaceVim ] [17:11:17] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:11:30] [ Info ] change to root:/home/tristan/RandomCode
[ SpaceVim ] [17:11:54] [ Info ] Start to find root for: /tmp/nvimfYGT79/3/issue_report.md
[ SpaceVim ] [17:11:54] [ Info ] change to root:/home/tristan/RandomCode
```
</details>

**Comment by LuisJoseSanchez** [comment]
Same problem.

**Comment by wywl99** [comment]
Same problem.

**Comment by bobby-b-song** [comment]
> Same problem.

Consider deleting all dot files (e.g. `.settings/`) under the root path
