### ISSUE TITLE
No syntax highlighting in .tsx files

### ISSUE THREAD

**Issue by osenvosem** [wsdjeg/SpaceVim#3631]
Although the layer is configured

```
[[layers]]
name = "lang#typescript"
```

there is no syntax highlighting

![Screenshot 2020-07-14 at 18 24 33](https://user-images.githubusercontent.com/6762673/87444368-60d31500-c5ff-11ea-9ab7-9565f0a96585.jpg)

**Comment by abhishiv** [comment]
Yup, manually doing `:setfiletype typescript.tsx` for now. 

Anyone knows a stable workaround?

**Comment by Rom1deTroyes** [comment]
You can use something like this in your [bootstrap function](https://spacevim.org/documentation/#bootstrap-functions) :

```viml
au BufNewFile,BufRead *.tsx set ft=typescript
```

Than SpaceVim will set a `typescript` `ft`( file type) to all `.tsx` files you open (well, for all buffers relating to a *.tsx).

**Comment by osenvosem** [comment]
Why the issue has been closed while it hasn't been solved at the editor level?

The solution above doesn't really solve the highlighting issue.

My vim configuration in comparison to the solution above:

![Screenshot 2020-07-19 at 17 48 41](https://user-images.githubusercontent.com/6762673/87877681-542c3380-c9e8-11ea-8401-6d834861bf6a.jpg)
![Screenshot 2020-07-19 at 17 48 36](https://user-images.githubusercontent.com/6762673/87877683-55f5f700-c9e8-11ea-8dbb-8cdc72ad6f2a.jpg)

**Comment by wsdjeg** [comment]
au BufNewFile,BufRead *.tsx set ft=typescript 

put the above into bootstrap after function should fix this issue.

**Comment by osenvosem** [comment]
@wsdjeg it is there. This doesn't solve the highlighting issue.

![Screenshot 2020-07-21 at 15 56 05](https://user-images.githubusercontent.com/6762673/88057527-e1979100-cb6a-11ea-991e-978003eb60c5.jpg)

**Comment by wsdjeg** [comment]
You should check the &filetype option of your jsx file. use `:echo &ft`.

**Comment by osenvosem** [comment]
@wsdjeg the result of `:echo &ft` command is `typescript`, but it should be `typescriptreact` as it is with an usual vim config.

**Comment by wsdjeg** [comment]
@osenvosem @Rom1deTroyes I have fixed this issue in https://github.com/SpaceVim/SpaceVim/pull/3993

![image](https://user-images.githubusercontent.com/13142418/100893411-4e963c80-34f6-11eb-88e2-d94c6fb1a238.png)
