### ISSUE TITLE
How can I install it only for neovim?

### ISSUE THREAD

**Issue by Elinos** [wsdjeg/SpaceVim#37]
I have other vim configuration, but I wanted to test neovim and SpaceVim will be handy to add some nice defaults. The problem is that as far as I can see in the install script it will install it for both vim and neovim. How I can only install for neovim?

**Comment by Elinos** [comment]
I actually tried to do `git clone https://github.com/SpaceVim/SpaceVim.git ~/.config/nvim`, but I gave me some error(even when I try to `:call deil#Install()` I get error.
```
Error detected while processing function <SNR>46_install_async[5]..<SNR>46_check_loop[15]..<SNR>46_check_output[2]..<SNR>46_get_async_result[9]..20:
line    1:
E121: Undefined variable: v:null
```
So how to uninstall/install it properly or just fix the error :)

**Comment by wsdjeg** [comment]
SpaceVim use dein as default package manager. as doc of dein says . you should has rsync in PATH. 

https://github.com/Shougo/dein.vim/blob/master/README.md

Thanks for feedback.  Readme should be update for this. sorry.

**Comment by Elinos** [comment]
`which rsync` returns `rsync: aliased to noglob rsync`
Not sure what else I need to do in order to make dein work :)

**Comment by Shougo** [comment]
@Elinos I have fixed the error in the latest dein.vim.

**Comment by Elinos** [comment]
@Shougo any hints how I can update to/use the latest dein.vim? Because I still get this error when I issue dein#install()

**Comment by Shougo** [comment]
Please update dein.vim.
I think your Vim version is very old(Vim 7.4).
You should update Vim version.

**Comment by wsdjeg** [comment]
you can run gir pull in dein cache dir. it should be ~/.cache/vimfiles/repos/github.com/Shougo/dein.vim
