### ISSUE TITLE
Error detected while processing function SpaceVim#custom#load//Please help me

### ISSUE THREAD

**Issue by wangkeunoh** [wsdjeg/SpaceVim#4394]
## Debug info
.

## Screenshots

![image](https://user-images.githubusercontent.com/19212686/129434876-e871974b-385a-4896-b05f-a406a1dee6f5.png)

**Comment by wangkeunoh** [comment]
Hello , My os information is as below.
wangkeun@Virtual-PC1:~/sw_certi$ cat /etc/issue
**Ubuntu 20.04.3 LTS \n \l**

and I installed 'spacevim' through below command 
**curl -sLf https://spacevim.org/install.sh | bash**

Thank you

**Comment by LMWL-HL** [comment]
This is a Bug.
Before the developer update, you can fix it by the follow steps:

> 1. modify `~/.SpaceVim/autoload/SpaceVim/custom.vim` in line `236`
`let local_conf_cache = s:FILE.unify_path(expand(g:spacevim_data_dir.'/SpaceVim/conf/' . fnamemodify(resolve(local_conf), ':t:r') . '.json'))`
to
`let local_conf_cache = s:FILE.unify_path(expand(g:spacevim_data_dir.'SpaceVim/conf/' . fnamemodify(resolve(local_conf), ':t:r') . '.json'))`

> 2. if `~/.cache/SpaceVim` don't have `conf` directory, then create it.
`mkdir ~/.cache/SpaceVim/conf`

**Comment by wangkeunoh** [comment]
Dear  LMWL-HL

Thank you so much 
As soon as I do it in the way you told me, it works fine.

Thank you so much and I hope you have a nice day.

**Comment by khaoskosmos** [comment]
Why are these types of errors getting merged? I'm not familiar with this process...

**Comment by dclong** [comment]
Encountering the same issue here.

**Comment by wsdjeg** [comment]
This has been fixed.

**Comment by craldaz** [comment]
I created the conf folder but when I do it doesn't give an error anymore but ignores the gruvbox Spacevim theme (I'm new to Spacevim so I don't know if any other thing is wrong).

**Comment by wsdjeg** [comment]
This issue has been fixed, and please update spacevim.

**Comment by porteron** [comment]
Just installed on macos, getting the same issue

**Comment by craldaz** [comment]
@porteron  I am also still getting the issue. If I create the conf folder it totally ruins the themes. Help would be appreciated! Thanks

**Comment by LMWL-HL** [comment]
Maybe you can remove it and reinstall it.The developer has fixed the bug.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 中午12:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SpaceVim/SpaceVim] Error detected while processing function SpaceVim#custom#load//Please help me (#4394)





 
@porteron  I am also still getting the issue. If I create the conf folder it totally ruins the themes. Help would be appreciated! Thanks
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LMWL-HL** [comment]
Maybe you can remove it and reinstall it.The developer has fixed the bug.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicholas ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 上午7:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SpaceVim/SpaceVim] Error detected while processing function SpaceVim#custom#load//Please help me (#4394)





 
Just installed on macos, getting the same issue
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LMWL-HL** [comment]
Maybe you can remove it and reinstall it.The developer has fixed the bug.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 凌晨1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SpaceVim/SpaceVim] Error detected while processing function SpaceVim#custom#load//Please help me (#4394)





 
I created the conf folder but when I do it doesn't give an error anymore but ignores the gruvbox Spacevim theme (I'm new to Spacevim so I don't know if any other thing is wrong).
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LMWL-HL** [comment]
Thank you for your efforts!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 晚上8:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SpaceVim/SpaceVim] Error detected while processing function SpaceVim#custom#load//Please help me (#4394)





 This issue has been fixed, and please update spacevim. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by svatem1** [comment]
Hi, I have similar problem with latest SpaceVim & neovim on Macos, the problem seems to be the directories that SpaceVim creates in .cache directory for some reason have weird rights: d-w-r-xr--, so SpaceVim is then not even able to read it..

**Comment by jmsmistral** [comment]
Same - I can confirm this is happening when running on Ubuntu within WSL. The directory ~/.cache/SpaceVim/ and subdirectories are created with weird permissions.

**Comment by ZhaoZuohong** [comment]
Same +1. Linux Mint 21, Neovim 0.7.2, directory `~/.cache/SpaceVim` and all its subdirectories have permission `d-w-rwxr-T`.

**Comment by IAMDAVID0920** [comment]
> Hi, I have similar problem with latest SpaceVim & neovim on Macos, the problem seems to be the directories that SpaceVim creates in .cache directory for some reason have weird rights: d-w-r-xr--, so SpaceVim is then not even able to read it..

Thank you sir~
This works for me:
`chmod 755 ~/.cache/SpaceVim/conf/`
And now i get:
`drwxr-xr-x   2 xxxxx  staff   64 Oct 16 16:57 conf`
