### ISSUE TITLE
Can't create file 

### ISSUE THREAD

**Issue by nightdoger** [wsdjeg/SpaceVim#4407]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

when I installed and run "vim" and refer these.
Error detected while processing /home/***/.SpaceVim/vimrc[25]../home/***/.SpaceVim/main.vim[69]..function SpaceVim#custom#load:
line   16:
E482: Can't create file /home/***/.cache//SpaceVim/conf/_home_shhanbin__SpaceVim_d_init_toml.json

**Comment by wsdjeg** [comment]
This issue has been fixed, please update spacevim.

**Comment by porteron** [comment]
Just installed on macos and seeing the same error
```
➜  ~ vim
Error detected while processing function SpaceVim#custom#load:
line   16:
E482: Can't create file /Users/<user>/.cache/SpaceVim/conf/_Users_<user>__SpaceVim_d_init_toml.json

```
Already tried deleting and reinstalling and still getting the same issue.
