### ISSUE TITLE
Error on attempt to execute current file(Python)

### ISSUE THREAD

**Issue by human1ty** [wsdjeg/SpaceVim#4625]
Faced Error - "E928: String required" attempt to execute current file
Note, it is possible to get the file run via RELP(sending current buffer)

## Expected behavior
Currently opened file is executed via python interpreter with no error

## The reproduce ways from Vim starting (Required!)
install SpaceVim with neovim option
$ curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim
Configure for python - install python packages and add layer for python and setup interpreter
manual https://spacevim.org/use-vim-as-a-python-ide/#enable-language-layer
```[[layers]]
name = "lang#python"
python_interpreter = '/usr/bin/python'
```
create sample file
```$ echo print\(\"hello\"\) > main.py```
start spacevim
```$ nvim```
execute current file via the keystroke sequence - SPC l r

## Screenshots
https://0x0.st/obaf.png

**Comment by wsdjeg** [comment]
@human1ty This has been fixed, please update spacevim.

**Comment by human1ty** [comment]
> 
didn't resolve.
1) curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
2) curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim
3) checked line 188 in .SpaceVim/autoload/SpaceVim/plugins/runner.vim whether it reflects the fix - it is

now it returns - https://0x0.st/ocN7.png
