### ISSUE TITLE
Some error with logger.vim

### ISSUE THREAD

**Issue by jkw** [wsdjeg/SpaceVim#466]
## Expected behavior, english is recommend
Uh.. Install properly?

## Environment Information
- OS: Linux
- vim version: 8.0
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)
1. Follow installation instructions.
2. Try to start vim/nvim.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
Fel upptäcktes vid bearbetning av /home/jkw/.SpaceVim/autoload/SpaceVim/logger.vim:
rad    1:
E121: Odefinierad variabel: g:spacevim_debug_level
E15: Ogiltigt uttryck: g:spacevim_debug_level
Fel upptäcktes vid bearbetning av function zvim#util#source_rc:
rad    2:
E171: :endif saknas
Tryck RETUR eller skriv kommando för att fortsätta

**Comment by wsdjeg** [comment]
I can not understand, and I think you spacevim is broken, reinstall it. please.

**Comment by jkw** [comment]
Did. Several times. Don't know what I do wrong?

Den mån 24 apr. 2017 15:00Wang Shidong <notifications@github.com> skrev:

**Comment by jkw** [comment]
Could not attach pictures, here's a link: SpaceVim https://imgur.com/gallery/NcMyU

**Comment by wsdjeg** [comment]
`rm -rf ~/.config/nvim` should fix this.

**Comment by dapolinario** [comment]
Same mistake over here. The removal of the `~/.config/nvim` directory also did not solve the problem.

**Comment by jkw** [comment]
Tried that, then made a clean install. Same error?

Den mån 24 apr. 2017 16:20Wang Shidong <notifications@github.com> skrev:

**Comment by wsdjeg** [comment]
I have fixed this issue, please update spacevim.

**Comment by dapolinario** [comment]
Clean installation after fix, same error:

```
~ $ env LANG=C nvim
Error detected while processing /home/dapolinario/.SpaceVim/autoload/SpaceVim/logger.vim:
line    1:
E121: Undefined variable: g:spacevim_debug_level
E15: Invalid expression: g:spacevim_debug_level
Error detected while processing function zvim#util#source_rc:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by jkw** [comment]
Exactly the same for me. Removed all dotfiles and dotfolders related to
vim/nvim. Same error message, but mine is in Swedish.

Den mån 24 apr. 2017 18:42Daniel Apolinario <notifications@github.com>
skrev:

**Comment by wsdjeg** [comment]
I have fixed it,  please check the context in `~/.SpaceVim/autoload/SpaceVim/logger.vim`. the first line should be 

https://github.com/SpaceVim/SpaceVim/commit/e14b7208ff92b923d6f19b87be92214b13c08528

**Comment by jkw** [comment]
```
┌[jkw☮nifto]-(~/.config/nvim/autoload)-[git://dev ✔]-
└> head -1 SpaceVim/logger.vim
let s:logger_level = get(g:, 'spacevim_debug_level', 1)
┌[jkw☮nifto]-(~/.config/nvim/autoload)-[git://dev ✔]-
└> nvim
Fel upptäcktes vid bearbetning av function SpaceVim#logger#error:
rad    1:
E121: Odefinierad variabel: g:spacevim_enable_debug
E15: Ogiltigt uttryck: g:spacevim_enable_debug && s:logger_level <= 3
Fel upptäcktes vid bearbetning av function zvim#util#source_rc:
rad    2:
E171: :endif saknas
Tryck RETUR eller skriv kommando för att fortsätta
```
