### ISSUE TITLE
SpaceVim don't skip fancy startify screen

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#4706]
## Expected behavior, english is required

When I start SpaceVim with some filename passed to it as arguments via command line. I want SpaceVim skip the fancy startify screen as the documentation startify.txt said.
https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/bundle/vim-startify/doc/startify.txt#L48

## The reproduce ways from Vim starting (Required!)

Start SpaceVim from command line. Such as `nvim-qt Sample.txt`.  Then SpaceVim starts with the fancy startify screen opened. I have to type `q` to skip the fancy startify screen.

**Comment by wsdjeg** [comment]
this should be fixed, please check it.

**Comment by xylinkun** [comment]
> this should be fixed, please check it.

It seems that the issue still exists.
![image](https://user-images.githubusercontent.com/5350867/192138644-7deaa00a-48df-4be7-9277-869c2d615c08.png)

**Comment by wsdjeg** [comment]
What is the reproduce step?

**Comment by xylinkun** [comment]
> What is the reproduce step?

Same as before.

**Comment by scil** [comment]
sollution:

```
let g:spacevim_disabled_plugins = ['vim-startify']
```

 @wsdjeg in https://github.com/SpaceVim/SpaceVim/issues/1640#issuecomment-383387773_

**Comment by xylinkun** [comment]
> sollution:
> 
> ```
> let g:spacevim_disabled_plugins = ['vim-startify']
> ```
> 
> @wsdjeg in [#1640 (comment)](https://github.com/SpaceVim/SpaceVim/issues/1640#issuecomment-383387773)_

That's not really a solution.
