### ISSUE TITLE
Haskell: E15: Invalid expression: systemlist('stack --verbosity silent path --project-root')[0]

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#475]
## Expected behavior
No errors

The error message here:
```log
"rock.hs" 1L, 30C written
Error detected while processing function neomake#Make[18]..<SNR>224_Make[33]..ne
omake#GetEnabledMakers[28]..neomake#GetMaker[23]..neomake#makers#ft#haskell#hdev
tools:
line   22:
E684: list index out of range: 0
E15: Invalid expression: systemlist('stack --verbosity silent path --project-roo
t')[0]
Error detected while processing function neomake#Make[18]..<SNR>224_Make:
line   33:
E171: Missing :endif
```

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
1. Open a new file called : `rock.hs`:

```haskell
main = do
    putStrLn "Hello, what's your name?"
    name <- getLine
    putStrLn("Hey " ++ name ++ ", you rock!")
```

2. Save it.
![image](https://cloud.githubusercontent.com/assets/12933851/25527910/9be6764a-2c4d-11e7-9ceb-e18121e74e9c.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

I don't think it is useful for now.

## init.vim

```viml
let g:spacevim_colorscheme  =   'molokai'
let g:spacevim_max_column   =   80
let g:spacevim_error_symbol =   '✗'
let g:spacevim_buffer_index_type = 4
let g:spacevim_lint_on_the_fly = 0
let g:spacevim_custom_plugins=[
            \ ['JamshedVesuna/vim-markdown-preview', {'on_ft' : 'markdown'}],
            \]
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#markdown')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('core#banner')
"call SpaceVim#layers#load('tmux')
nnoremap <leader>svf :source ~/.SpaceVim.d/init.vim<cr>
let g:neomake_open_list = 0
let g:mkdp_path_to_chrome = 'google-chrome-stable'
let g:mkdp_auto_start = 0
let vim_markdown_preview_github=1
let vim_markdown_preview_use_xdg_open=1
```

**Comment by wsdjeg** [comment]
It is issue of neomake, I think plugin should check the result of `system()` or `systemlist()`, use index only if the result is not empty.

cc @blueyed

**Comment by blueyed** [comment]
@Gabirel 
What does `stack --verbosity silent path --project-root` give you?  Nothing?
Do you have `stack` installed after all?

**Comment by Gabirel** [comment]
@blueyed 

1. Yes, I have `stack` installed.

2. No results from `stack --verbosity silent path --project-root`

**Comment by blueyed** [comment]
@Gabirel 
Just for your information: I am transforming this into an issue for Neomake (where you should have reported it in the first place), and have to type/copy the error message from your screenshot.  That is not cool.  Please provide error messages as text when reporting issues.  It makes it also possible to find issues when searching for them actually.

https://github.com/neomake/neomake/issues/1262

**Comment by Gabirel** [comment]
@blueyed 
I'm sorry about this. I can't tell whether it's a bug of `neomake` or something else. So that's why I submit the issue here firstly.
Next time, I will post the error messages as text. Thanks for letting me know this. I'll pay attention to this.

**Comment by wsdjeg** [comment]
@Gabirel can you test the latest of neomake, I think this issue has been fixed.

**Comment by Gabirel** [comment]
@wsdjeg I've tested long time ago. No, this issue isn't been fixed very well. I can still reproduce.

**Comment by blueyed** [comment]
The suggested fix from me (https://github.com/neomake/neomake/pull/1263) has not been merged yet.
It is not clear to me if `stack --verbosity silent path --project-root` should be assumed to be empty etc.

There are some comments from @bonds at https://github.com/neomake/neomake/pull/1263#discussion_r114088324.

**Comment by blueyed** [comment]
@Gabirel 
Can you provide more steps to reproduce this?
I.e. how is your project setup?
Are you using stack for it, or is `stack` just installed (but not used)?

**Comment by Gabirel** [comment]
@blueyed 

## Answer
1. I didn't set up my project at all. Only one single `*.hs` source file.
2. I haven't use `stack` yet. So, `stack` is only just installed without being used.

## More step to reproduce
1. Create a new file. Let's call: `rock.hs`:

```haskell
main = do
    putStrLn "Hello, what's your name?"
    name <- getLine
    putStrLn("Hey " ++ name ++ ", you rock!")
```

2. Press `:w` to save it
![image](https://cloud.githubusercontent.com/assets/12933851/26045317/31948426-397c-11e7-9ca5-e04b5caf5ff9.png)

*Note: It still has errors even if you save an empty `*.hs` file*
## Video
https://asciinema.org/a/aou5uvfbiwvxmkkk637qnnncn

**Comment by blueyed** [comment]
@Gabirel 
Thanks for the clarification.  I've merged https://github.com/neomake/neomake/pull/1263#issuecomment-301937489 now based on that.
It should hopefully fix your use case.

**Comment by Gabirel** [comment]
@blueyed Thanks for your work. It works :+1:
