### ISSUE TITLE
globals-command will not find gtags database

### ISSUE THREAD

**Issue by badamowicz** [wsdjeg/SpaceVim#4828]
## Expected behavior

The `globals` command finds references inside `gtags` database.

## Environment Information

- OS: linux
- vim version: 8.1(1-2269, 3612, 3625, 3669, 3741)
- neovim version: -
- SpaceVim version: 2.2.0-dev
- SpaceVim status: cd45afc4

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

* Open an arbitrary project (no matter which language) at its sources root.
* Create the tags databases with `SPC m g c`
* Check if the tags database files have been created correctly with the current time:
```bash
bernd@bernd-vm ~ $ ls -l .cache/SpaceVim/tags/
total 72
-rw-r--r-- 1 bernd bernd 16384 Apr  4 11:59 GPATH
-rw-r--r-- 1 bernd bernd 16384 Apr  4 11:59 GRTAGS
-rw-r--r-- 1 bernd bernd 16384 Apr  4 11:59 GTAGS
```
(Isn't it strange they all have the same size?)

* Now try to find any symbol within the code with `SPC m g d`. This will issue this error:

`Error: global command failed. command line: global --result=ctags-x -qde 'Opensearch'`

* Issuing the same command in the same directory on command line but without the quiet flag gives:

```bash
$ global --result=ctags-x -de 'Opensearch'
global: GTAGS not found.
```

Also tried `export GTAGSLIBPATH=/home/bernd/.cache/SpaceVim/tags/` before starting vim, but with no success.

Any ideas?

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'jellybeans'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/bernd/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/bernd/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'dracula'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', 'pom.xml', 'build.gradle', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  auto_completion_enable_snippets_in_popup=0
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_interpreter='/usr/bin/python'
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#java"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=NONE', '-noverify', '-Xm
x1G', '-jar', '/opt/Eclipse-JDT/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar', '-configuration', '/opt/Eclipse-JDT/config_linux/', '-data', '/home/bernd/.cache/javalsp']}
  filetypes=['java']
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
  gtagslabel='pygments'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#python`:ok
  - `lang#javascript`:ok
  - `lang#java`:ok
  - `lsp`:ok
  - `colorscheme`:ok
  - `gtags`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:43:40] [   0.001] [  Info ] Loading SpaceVim from: /home/bernd/.SpaceVim/
[ SpaceVim ] [11:43:40] [   0.314] [  Info ] Startup with argv: 2
[ SpaceVim ] [11:43:40] [   0.353] [  Info ] start loading global config >>>
[ SpaceVim ] [11:43:40] [   0.353] [  Info ] global_dir is: /home/bernd/.SpaceVim.d/
[ SpaceVim ] [11:43:40] [   0.353] [  Info ] find global config: /home/bernd/.SpaceVim.d/init.toml
[ SpaceVim ] [11:43:40] [   0.355] [  Info ] start to apply config [glob]
[ SpaceVim ] [11:43:40] [   0.361] [  Info ] start loading local config >>>
[ SpaceVim ] [11:43:40] [   0.361] [  Info ] Could not find project local config
[ SpaceVim ] [11:43:40] [   0.461] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:43:40] [   0.520] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:43:40] [   0.521] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [11:43:40] [   0.623] [  Info ] Load projects cache from: /home/bernd/.cache/SpaceVim/projects.json
[ SpaceVim ] [11:43:40] [   0.632] [  Info ] lsp client: vim-lsp
[ SpaceVim ] [11:43:41] [   0.748] [  Info ] finished loading SpaceVim!
[   rooter ] [11:43:41] [   1.134] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/issue.tmp
[   rooter ] [11:43:41] [   1.146] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/issue.tmp
[ SpaceVim ] [11:43:41] [   1.154] [  Info ] run root changed callback on VimEnter!
[   rooter ] [11:46:34] [ 174.068] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/issue.tmp
[   rooter ] [11:46:34] [ 174.107] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/issue.tmp
[    ctags ] [11:46:34] [ 174.128] [  Info ] start to check ctags version
[    ctags ] [11:46:34] [ 174.151] [  Info ] ctags version checking done:
[    ctags ] [11:46:34] [ 174.151] [  Info ]       ctags bin:ctags
[    ctags ] [11:46:34] [ 174.151] [  Info ] update ctags database for /home/bernd/Develop/cs-api-scraper/src
[    ctags ] [11:46:34] [ 174.188] [  Info ] ctags database updated successfully
[   rooter ] [11:46:55] [ 195.383] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/
[ SpaceVim ] [11:46:55] [ 195.460] [  Info ] key binding guide float statusline winid:1003
[ SpaceVim ] [11:46:57] [ 197.513] [  Info ] close float statusline winid:1003
[   rooter ] [11:46:57] [ 197.516] [  Info ] Start to find root for: /home/bernd/Develop/cs-api-scraper/src/
[ SpaceVim ] [11:46:57] [ 197.576] [  Info ] key binding guide float statusline winid:1005
[ SpaceVim ] [11:47:01] [ 201.137] [  Info ] close float statusline winid:1005
[   rooter ] [11:47:01] [ 201.296] [  Info ] Start to find root for: /tmp/vQXvQ5R/8/issue_report.md
[ SpaceVim ] [11:47:01] [ 201.688] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:47:01] [ 201.705] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:47:01] [ 201.706] [  Info ] the func has been added to mode:paste-mode
```
</details>

**Comment by wsdjeg** [comment]
hi @badamowicz it seems a bug, the gtags databasse should be created in sub path instead of `~/.cache/SpaceVim/tags/`.

**Comment by badamowicz** [comment]
Hi @wsdjeg ! Thanks for taking care of this! Looking forward to have the fix merged.

**Comment by wsdjeg** [comment]
@badamowicz I just add more debug log about it. but it still does not work: here is debug info from #4843 

```
[    gtags ] [00:05:22:599] [ Debug ] start to update gtags database
[    gtags ] [00:05:22:600] [ Debug ]             dir:C:/Users/wsdjeg/.cache/SpaceVim/tags/C__Users_wsdjeg__SpaceVim_
[    gtags ] [00:05:22:600] [ Debug ]          single:1
[    gtags ] [00:05:22:600] [ Debug ]       gtags cmd:['gtags', '--single-update', 'C:\Users\wsdjeg\.SpaceVim\bundle\gtags.vim\autoload\gtags.vim', '-O', 'C:/Users/wsdjeg/.cache/SpaceVim/tags/C__Users_wsdjeg__SpaceVim_']
[    gtags ] [00:05:22:621] [ Debug ]    gtags job id:13
[    gtags ] [00:05:29:505] [ Debug ] gtags global command: Gtags -f %
[    gtags ] [00:05:29:506] [ Debug ] $GTAGSROOT is: C:/Users/wsdjeg/.SpaceVim/
[    gtags ] [00:05:29:506] [ Debug ] $GTAGSDBPATH is: C:/Users/wsdjeg/.cache/SpaceVim/tags/C__Users_wsdjeg__SpaceVim_
[    gtags ] [00:05:29:506] [ Debug ] cmd is: global --result=ctags-x -qf "bundle\gtags.vim\autoload\gtags.vim"
[    gtags ] [00:05:29:572] [ Debug ] failed to run, v:shell_error is 1
[    gtags ] [00:05:38:673] [ Debug ] gtags global command: Gtags -P
[    gtags ] [00:05:38:674] [ Debug ] $GTAGSROOT is: C:/Users/wsdjeg/.SpaceVim/
[    gtags ] [00:05:38:674] [ Debug ] $GTAGSDBPATH is: C:/Users/wsdjeg/.cache/SpaceVim/tags/C__Users_wsdjeg__SpaceVim_
[    gtags ] [00:05:38:674] [ Debug ] cmd is: global --result=ctags-x -qPe ""
[    gtags ] [00:05:38:735] [ Debug ] failed to run, v:shell_error is 1

```

and here is info of `ls -l` in `C:/Users/wsdjeg/.cache/SpaceVim/tags/C__Users_wsdjeg__SpaceVim_`. the gtags database is generated from `SPC m g c` 

```
C:\Users\wsdjeg\.cache\SpaceVim\tags\C__Users_wsdjeg__SpaceVim_>ls -l
total 15452
-rw-r--r-- 1 wsdjeg Administrators  3604480 Apr 19 23:51 GPATH
-rw-r--r-- 1 wsdjeg Administrators   409600 Apr 19 23:51 GRTAGS
-rw-r--r-- 1 wsdjeg Administrators   155648 Apr 19 23:51 GTAGS
-rw-r--r-- 1 wsdjeg Administrators 11652118 Apr 20 00:08 tags

```

**Comment by wsdjeg** [comment]
```diff
diff --git a/bundle/gtags.vim/autoload/gtags.vim b/bundle/gtags.vim/autoload/gtags.vim
index 959b255b..c7820d8b 100644
--- a/bundle/gtags.vim/autoload/gtags.vim
+++ b/bundle/gtags.vim/autoload/gtags.vim
@@ -215,13 +215,13 @@ endfunction
 function! s:ExecGlobal(cmd) abort
   let l:restore_gtagsroot = 0
   if empty($GTAGSROOT)
-    let $GTAGSROOT = SpaceVim#plugins#projectmanager#current_root()
+    let $GTAGSROOT = getcwd()
     let l:restore_gtagsroot = 1
   endif
 
   let l:restore_gtagsdbpath = 0
   if empty($GTAGSDBPATH)
-    let $GTAGSDBPATH = s:FILE.unify_path(g:tags_cache_dir) . s:FILE.path_to_fname($GTAGSROOT)
+    let $GTAGSDBPATH = 'C:\Users\wsdjeg\.cache\SpaceVim\tags\'. s:FILE.path_to_fname($GTAGSROOT)
     let l:restore_gtagsdbpath = 1
   endif
 
```

after change path sep, everything works well:

```
[ SpaceVim ] [00:00:20:026] [ Info  ] close float statusline winid:1008
[    gtags ] [00:00:20:093] [ Debug ] start to update gtags database
[    gtags ] [00:00:20:093] [ Debug ]             dir:C:/Users/wsdjeg/.cache/SpaceVim/tags/d__me_languages_c_hello_
[    gtags ] [00:00:20:093] [ Debug ]          single:0
[    gtags ] [00:00:20:093] [ Debug ]       gtags cmd:['gtags', '--skip-unreadable', '-O', 'C:/Users/wsdjeg/.cache/SpaceVim/tags/d__me_languages_c_hello_']
[    gtags ] [00:00:20:111] [ Debug ]    gtags job id:9
[ SpaceVim ] [00:00:22:832] [ Info  ] key binding guide float statusline winid:1010
[ SpaceVim ] [00:00:22:856] [ Info  ] close float statusline winid:1010
[ SpaceVim ] [00:00:22:920] [ Info  ] key binding guide float statusline winid:1012
[ SpaceVim ] [00:00:23:324] [ Info  ] close float statusline winid:1012
[ SpaceVim ] [00:00:23:387] [ Info  ] key binding guide float statusline winid:1014
[ SpaceVim ] [00:00:24:923] [ Info  ] close float statusline winid:1014
[    gtags ] [00:00:24:925] [ Debug ] gtags global command: Gtags -P
[    gtags ] [00:00:24:926] [ Debug ] $GTAGSROOT is: d:\me\languages\c\hello
[    gtags ] [00:00:24:926] [ Debug ] $GTAGSDBPATH is: C:\Users\wsdjeg\.cache\SpaceVim\tags\d__me_languages_c_hello_
[    gtags ] [00:00:24:926] [ Debug ] cmd is: global --result=ctags-x -qPe ""

```

**Comment by wsdjeg** [comment]
@badamowicz the PR is merged, and I have test it in wsl2, it works well for me, but still does not work in win 11 now.

**Comment by badamowicz** [comment]
@wsdjeg : Thanks for the fix! However, doesn't work for me. Updated Spacevim to 2.2.0-dev-88c885bb which contains your fix f1c5d98, but it still doesn't find the Gtags DB. I can see it's generated below ` ~/.cache/SpaceVim/tags/`. So from my point of view nothing changed actually.
