### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by xndyz** [wsdjeg/SpaceVim#548]
## Expected behavior, english is recommend
Plugin installation succeeds when I open Vim. Is there something I did to mess up the state?

## Environment Information
- OS: MacOS Sierra
- vim version: Latest
- neovim version: Latest

## The reproduce ways from Vim starting (Required!)
![image](https://cloud.githubusercontent.com/assets/19108762/26284716/d1e36b4e-3e0f-11e7-9aa4-679a54ecf73c.png)

## Recording

https://asciinema.org/a/4n8058xo7mz17nix4nv08t6yj

**Comment by wsdjeg** [comment]
how about start vim by `vim --cmd "set maxfuncdepth=1000"`?

**Comment by leojrfs** [comment]
@wsdjeg this is what I was talking about on gitter.

With `vim --cmd "set maxfuncdepth=1000"` the behaviour is the same.

vim 8.0.0596:
![screen shot 2017-05-22 at 00 26 01](https://cloud.githubusercontent.com/assets/1101457/26288227/533b5236-3e85-11e7-8b27-1d45d7ed5599.png)

neovim HEAD-3280765:

![screen shot 2017-05-22 at 00 29 04](https://cloud.githubusercontent.com/assets/1101457/26288249/abd04dde-3e85-11e7-80bd-a4ee824e794c.png)

**Comment by wsdjeg** [comment]
how about set to 5000？ hmm this snhould happen only when your vim has no py and job support.

**Comment by wsdjeg** [comment]
oop, It is bug of status line, I will fix it.

**Comment by tkossak** [comment]
same problem on Linux Mint and vim 7.4. My vim has +job and +python3.

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
3
```

**Comment by xndyz** [comment]
`vim --cmd "set maxfuncdepth=1000"` fixed it for me, not sure why it's not working for @tkossak though.

**Comment by tkossak** [comment]
I had to run `vim --cmd "set maxfuncdepth=1000"` few times, eventually increasing it to 10000 and then it worked.

**Comment by wsdjeg** [comment]
Fixed in #551

**Comment by leojrfs** [comment]
It still doesn't solve all errors.
<img width="1214" alt="screen shot 2017-05-22 at 15 06 36" src="https://cloud.githubusercontent.com/assets/1101457/26312769/9102bee4-3f00-11e7-862e-5de20641a71f.png">

**Comment by wsdjeg** [comment]
@leojrfs It is feature of vim, vim only allow 200 loops when execute a command, so I think you should update your vim to vim 8

**Comment by leojrfs** [comment]
that screenshot is from vim 8.0.0596
