### ISSUE TITLE
statusline 和 tabline 显示错误

### ISSUE THREAD

**Issue by cuckootan** [wsdjeg/SpaceVim#608]
## Expected behavior, english is recommended

好像 statusline 中的 separator 设置无效。我设置为 arrow, curve 等都不能达到预期效果，都会有问号。只有设置为 nil 才不会有问号。
还有就是 tabline 中无论什么情况下都会有问号。

## Environment Information
- OS: macos 10.12.5
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)

let g:spacevim_statusline_separator = 'curve'

## Screenshots

<img width="1274" alt="screen shot 2017-06-07 at 12 01 25 am" src="https://user-images.githubusercontent.com/7947605/26839260-118119ec-4b15-11e7-8119-883b9d613350.png">

<img width="1280" alt="screen shot 2017-06-07 at 12 01 36 am" src="https://user-images.githubusercontent.com/7947605/26839274-1d04cbf6-4b15-11e7-9783-847b610edee0.png">

**Comment by wsdjeg** [comment]
read https://github.com/SpaceVim/SpaceVim/blob/dev/docs/documentation.md#statusline--tabline

and you need to install the powerline font

**Comment by cuckootan** [comment]
I fixed it after installing DejaVuSansMono font in [nerd fonts](https://github.com/ryanoasis/nerd-fonts). Thanks!

**Comment by Nicksxs** [comment]
i have installed powerline font ,but the problem is still there, could anyone help me

**Comment by wsdjeg** [comment]
as you set `let g:spacevim_statusline_separator = 'curve'`. you need to install  https://github.com/ryanoasis/powerline-extra-symbols

**Comment by Nicksxs** [comment]
@wsdjeg it fixed, i did ssh to my vps, and have installed powerline font in the vps but not in the local mac, then i installed it and change the text font of iterm2 to powerline font ,problem solved, thank you ~

**Comment by weilbith** [comment]
Same problem here. I have installed the all fonts successfully. Used the `install.sh` for it. A fast check with `fc-list` confirm this. For some reason not all chars are missing. Seems to be only the line separator. What can I do to fix this or check if everything is correct installed? I can post further information.
![spacevim_statusbar](https://user-images.githubusercontent.com/12543647/33186146-a6db30e8-d087-11e7-8fe9-2acb8205e84a.jpg)

**Comment by wsdjeg** [comment]
what is your os? can you install charmap to see the font info of a char?

**Comment by weilbith** [comment]
It's a _Ubuntu 16.4_ distribution.
Already installed. Which character I should analyse?

**Comment by wsdjeg** [comment]
Can you submit new issue?

**Comment by weilbith** [comment]
Sure. Will do this.
